branches:
  only:
  - python
sudo: false
language: python
python:
- pypy
- pypy3
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
install:
- pip install -e . "flake8 >= 2.4.0" "Werkzeug >= 0.9" coverage coveralls
script:
- coverage run --source sass,sassc,sassutils setup.py test
- flake8 .
after_success:
- coveralls
