language: python
python:
- pypy
- pypy3
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
install:
- pip install -rrequirements-dev.txt coveralls
script:
- coverage run --source sass,sassc,sassutils -m pytest sasstests.py
- flake8 .
after_success:
- coveralls
cache:
    directories:
        - $HOME/.cache/pip
