language: python
python:
- pypy
- pypy3
- 2.7
- 3.3
- 3.4
- 3.5
install:
- pip install -rrequirements-dev.txt coveralls
script:
- COVERAGE_PROCESS_START=$PWD/.coveragerc py.test sasstests.py
- coverage combine
- coverage report
- flake8 .
after_success:
- coveralls
cache:
    directories:
        - $HOME/.cache/pip
