version: "{build}"
environment:
  matrix:
  - PYTHON: "C:\\Python27"
  - PYTHON: "C:\\Python27-x64"
  - PYTHON: "C:\\Python34"
  - PYTHON: "C:\\Python34-x64"
  - PYTHON: "C:\\Python35"
  - PYTHON: "C:\\Python35-x64"
matrix:
  fast_finish: true
init:
- "ECHO %PATH%"
- "ECHO %PYTHON%"
- ps: "ls C:/Python*"
install:
- "git submodule update --init"
- "%PYTHON%\\Scripts\\pip.exe --version"
- "%PYTHON%\\Scripts\\pip.exe install -rrequirements-dev.txt wheel"
build: false
test_script:
- '%PYTHON%\\python.exe -c "import os, pprint; pprint.pprint(sorted(os.environ.items()))"'
- "%PYTHON%\\python.exe -m pytest sasstests.py"
after_test:
- "%PYTHON%\\python.exe setup.py bdist_wheel"
artifacts:
- path: dist\*
cache:
- '%LOCALAPPDATA%\pip\cache'
